// Generated by CoffeeScript 1.7.1
var LeapToFirebase, assert, debug, util, _;

LeapToFirebase = require('../src/sender/leap_to_firebase').LeapToFirebase;

_ = require('underscore');

assert = require('assert');

debug = require('debug')('test:leap_to_firebase');

util = require('util');

describe("Leap To Firebase", function() {
  var base_event, l2f;
  l2f = new LeapToFirebase;
  base_event = {
    user: 'string',
    stem: 'int',
    event: {},
    source: "leap"
  };
  return _.each([
    {
      type: 'pinch-start',
      value: {
        finger: 0,
        hand: 'left'
      }
    }, {
      type: 'pinch-start',
      value: {
        finger: 1,
        hand: 'left'
      }
    }, {
      type: 'pinch-stop',
      value: {
        finger: 0,
        hand: 'left'
      }
    }, {
      type: 'pinch-stop',
      value: {
        finger: 1,
        hand: 'left'
      }
    }
  ], function(pinch_event) {
    return it("takes a pinch command and outputs a track-on/off", function() {
      var actual, expected;
      expected = _.clone(base_event);
      expected.event = {
        type: "volume",
        level: pinch_event.type === 'pinch-start' ? 0 : 1
      };
      expected.stem = pinch_event.value.finger;
      actual = l2f.translate(pinch_event);
      return assert.deepEqual(actual, expected);
    });
  });
});
