// Generated by CoffeeScript 1.7.1
var LeapToFirebase, module;

LeapToFirebase = (function() {
  function LeapToFirebase(firebase_instance) {
    this.firebase_instance = firebase_instance;
    console.log("Construct LeapToFirebase. Connecting to " + firebase_instance);
  }

  LeapToFirebase.prototype.translate = function(leap_event) {
    if (leap_event.type === 'pinch-start') {
      return {
        user: 'string',
        stem: leap_event.value,
        event: {
          type: 'volume',
          level: 0
        },
        source: 'leap'
      };
    } else if (leap_event.type === 'pinch-stop') {
      return {
        user: 'string',
        stem: leap_event.value,
        event: {
          type: 'volume',
          level: 1
        },
        source: 'leap'
      };
    } else {
      return null;
    }
  };

  LeapToFirebase.prototype.sendToFirebase = function(event) {
    console.log("Sending event " + (JSON.stringify(event)) + " to firebase " + this.firebase_instance);
    return console.error("Not actually sending to firebase YET");
  };

  return LeapToFirebase;

})();

module = module || {};

module.exports = {
  LeapToFirebase: LeapToFirebase
};
