// Generated by CoffeeScript 1.7.1
var LeapToFirebase, module;

LeapToFirebase = (function() {
  function LeapToFirebase() {
    console.log("Construct LeapToFirebase");
  }

  LeapToFirebase.prototype.translate = function(leap_event) {
    if (leap_event.type === 'pinch-start') {
      return {
        user: 'string',
        stem: leap_event.value,
        event: {
          type: 'volume',
          level: 0
        },
        source: 'leap'
      };
    } else if (leap_event.type === 'pinch-stop') {
      return {
        user: 'string',
        stem: leap_event.value,
        event: {
          type: 'volume',
          level: 1
        },
        source: 'leap'
      };
    } else {
      return null;
    }
  };

  return LeapToFirebase;

})();

module = module || {};

module.exports = {
  LeapToFirebase: LeapToFirebase
};
