// Generated by CoffeeScript 1.7.1
var KeyTapListener, LeapEventListener, PinchListener, activeCommands, leapToFirebase, output, pinchHandler, progress,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

output = document.getElementById("output");

progress = document.getElementById("progress");

activeCommands = document.getElementById("activeCommands");

if (typeof LeapToFirebase === "undefined" || LeapToFirebase === null) {
  throw "No LeapToFirebase";
}

leapToFirebase = new LeapToFirebase(config.firebase_room_uri);

LeapEventListener = (function() {
  function LeapEventListener() {
    console.log("Setting up...");
  }

  LeapEventListener.prototype.listen = function() {
    return console.log("Listening for event");
  };

  LeapEventListener.prototype.sendEvent = function(type, value) {
    var firebaseEvent;
    console.log("Event: " + type + ", Value: " + (JSON.stringify(value)));
    firebaseEvent = leapToFirebase.translate({
      type: type,
      value: value
    });
    if (firebaseEvent != null) {
      return leapToFirebase.sendToFirebase(firebaseEvent);
    }
  };

  LeapEventListener.prototype.displayActiveCommand = function(text) {
    if (activeCommands) {
      return activeCommands.innerHTML = "<h1> " + text + " </h1>";
    }
  };

  return LeapEventListener;

})();

PinchListener = (function(_super) {
  __extends(PinchListener, _super);

  function PinchListener() {
    this.PINCH_STRENGTH_ON = .8;
    this.PINCH_STRENGTH_OFF = .4;
    console.log("Init pinch listener... Pinch On=" + this.PINCH_STRENGTH_ON + ", Off=" + this.PINCH_STRENGTH_OFF);
    this.pinched = false;
    this.pinched_finger = null;
  }

  PinchListener.prototype.findPinchingFingerType = function(hand) {
    var closest, current, distance, f, fingerIndex, pincher, _i;
    console.log("findPinchingFingerType");
    closest = 500;
    for (f = _i = 0; _i <= 4; f = ++_i) {
      current = hand.fingers[f];
      distance = Leap.vec3.distance(hand.thumb.tipPosition, current.tipPosition);
      if (current !== hand.thumb && distance < closest) {
        closest = distance;
        pincher = current;
        fingerIndex = f;
      }
    }
    return {
      pincher: pincher,
      fingerIndex: fingerIndex
    };
  };

  PinchListener.prototype.updateUi = function(pinchStrength) {
    if (output && progress) {
      output.innerHTML = pinchStrength;
      return progress.style.width = pinchStrength * 100 + "%";
    } else {
      return console.error("UI hooks aren't configured. output (" + output + "), progress (" + progress + ")");
    }
  };

  PinchListener.prototype.sendEvent = function(type, value) {
    console.log("Leap:Pinch event");
    this.displayActiveCommand(type, value);
    return PinchListener.__super__.sendEvent.call(this, type, value);
  };

  PinchListener.prototype.displayActiveCommand = function(type, value) {
    return PinchListener.__super__.displayActiveCommand.call(this, "" + type + " - " + value.hand + " " + value.finger);
  };

  PinchListener.prototype.listen = function(hands) {
    var fingerIndex, hand, pinchStrength, whichHand, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = hands.length; _i < _len; _i++) {
      hand = hands[_i];
      if (!hand) {
        continue;
      }
      whichHand = hand.type;
      pinchStrength = hand.pinchStrength.toPrecision(2);
      this.updateUi(pinchStrength);
      if (!this.pinched && pinchStrength > this.PINCH_STRENGTH_ON) {
        fingerIndex = this.findPinchingFingerType(hand).fingerIndex;
        this.pinched = true;
        this.pinched_finger = fingerIndex;
        _results.push(this.sendEvent('pinch-start', {
          finger: this.pinched_finger,
          hand: whichHand
        }));
      } else if (this.pinched && pinchStrength < this.PINCH_STRENGTH_OFF) {
        this.sendEvent('pinch-stop', {
          finger: this.pinched_finger,
          hand: whichHand
        });
        this.pinched = false;
        _results.push(this.pinched_finger = null);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  return PinchListener;

})(LeapEventListener);

KeyTapListener = (function(_super) {
  __extends(KeyTapListener, _super);

  function KeyTapListener() {
    console.log("Init KeyTapListener");
  }

  KeyTapListener.prototype.sendEvent = function(type, value) {};

  KeyTapListener.prototype.listen = function(gesture) {
    return console.log("key tap listen");
  };

  return KeyTapListener;

})(LeapEventListener);

pinchHandler = new PinchListener;

KeyTapListener = new KeyTapListener;

Leap.loop({
  enableGestures: true,
  background: true
}, function(frame) {
  var hands;
  hands = frame.hands[0] || frame.hands[1] ? frame.hands : null;
  if (hands) {
    return pinchHandler.listen(hands);
  }
});
